/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include <app-common/zap-generated/callback.h>

using namespace chip;

void __attribute__((weak)) emberAfAccessControlClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfAdministratorCommissioningClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfBasicInformationClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfDescriptorClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfDoorLockClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfGeneralCommissioningClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfGeneralDiagnosticsClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfGroupKeyManagementClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfIdentifyClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfLocalizationConfigurationClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfNetworkCommissioningClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfOperationalCredentialsClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfPowerSourceClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfUserLabelClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}

void __attribute__((weak)) emberAfWiFiNetworkDiagnosticsClusterInitCallback(EndpointId endpoint)
{
    /*To prevent warning*/
    (void) endpoint;
}
