/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Entry point for the application.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 ***********************************************************************************************************************/
#include "common_utils.h"
#include "hal_data.h"
#include "i2c_slave.h"

FSP_CPP_HEADER
void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    fsp_err_t err = FSP_SUCCESS;
    fsp_pack_version_t version = {RESET_VALUE};


    /* version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3,EP_VERSION);
    APP_PRINT(BANNER_4,FSP_VERSION_STRING);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);
    APP_PRINT(EP_INFO);

    /*  I2C master and slave driver initialization */
    err = init_i2c_driver();
    /* Handle error */
    if(FSP_SUCCESS != err)
    {
        /* I2C Master and Slave initialization failed  */
        APP_ERR_PRINT("\r\n ** I2C driver initialization FAILED ** \r\n");

        /* Turn ON LED */
        set_led(LED_ON);

        APP_ERR_TRAP(err);
    }

    while(true)
    {
        /* Performs on I2C slave read write operation */
        err = process_slave_WriteRead();

        /*
         * Perform clean_up - On slave i2c read write operation failure
         * Note: For Demonstration Purpose the failure ends up with TRAP.
         * Note: This can be handled in many ways as per the Application needs
         */
        if (FSP_SUCCESS != err)
        {
            /* print RTT message */
            APP_ERR_PRINT ("\r\n **I2C slave transaction Failed, closing open modules ** \r\n");

            /* de-initialize opened I2C module */
            deinit_i2c_driver();
            APP_ERR_TRAP(err);
        }

        /* 1 Seconds Wait time to recognize LED toggling between successive Read and Write operations. */
        R_BSP_SoftwareDelay(TOGGLE_DELAY, BSP_DELAY_UNITS_MILLISECONDS);
        
    }

#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses:
 *  - the event that is called after the clocks have been configured, to freeze the watchdog
 *  - the event that is called right before main() to set up the pins
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_CLOCK == event)
    {
        /* System clocks are configured. */

        /*
         * Freeze the watchdog, to avoid an unexpected reboot.
         * The watchdog-freeze setting must be enabled for this to have an effect.
         */
        R_BSP_PeripheralFreeze (BSP_FREEZE_PERIPHERAL_SYS_WDOG);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_GPIO_W_Open (&g_gpio_w_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
