/***********************************************************************************************************************
 * File Name    : hal_entry.c
 * Description  : Contains data structures and functions used in hal_entry.c.
 **********************************************************************************************************************/
/***********************************************************************************************************************
 * Copyright (c) 2020 - 2026 Renesas Electronics Corporation and/or its affiliates
 *
 * SPDX-License-Identifier: BSD-3-Clause
 ***********************************************************************************************************************/

#include "common_utils.h"
#include "crc_ep.h"
#include "hal_data.h"

FSP_CPP_HEADER
/* Flags to indicate UART Tx, Rx events */
static volatile bool w_uart_rxflag = false;
static volatile bool w_uart_txflag = false;

/* private functions */
static fsp_err_t crc_operation(void);
static fsp_err_t set_led(uint32_t onoff);

void R_BSP_WarmStart(bsp_warm_start_event_t event);
FSP_CPP_FOOTER

/*******************************************************************************************************************//**
 * main() is generated by the FSP Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */
    fsp_err_t err = FSP_SUCCESS;
    uint8_t rByte[BUFFER_SIZE_DOWN] = {RESET_VALUE};
    fsp_pack_version_t version = {RESET_VALUE};

    /* Version get API for FLEX pack information */
    R_FSP_VersionGet(&version);

    /* Example Project information printed on the Console */
    APP_PRINT(BANNER_1);
    APP_PRINT(BANNER_2);
    APP_PRINT(BANNER_3, EP_VERSION);
    APP_PRINT(BANNER_4, version.version_id_b.major, version.version_id_b.minor, version.version_id_b.patch);
    APP_PRINT(BANNER_5);
    APP_PRINT(BANNER_6);

    /* Open uart module */
    err = R_UART_W_Open(&g_uart_ctrl, &g_uart_cfg);
    /* handle error */
    if (FSP_SUCCESS != err)
    {
        /* Display failure message in RTT */
        APP_ERR_PRINT("R_UART_W_Open API FAILED \r\n");
        APP_ERR_TRAP(err);
    }

    /* Open CRC module*/
    err = R_CRC_W_Open(&g_crc_ctrl, &g_crc_cfg);

    /* handle error */
    if (FSP_SUCCESS != err)
    {
        /* close opened uart module*/
        deinit_uart();
        /* Display failure message in RTT */
        APP_ERR_PRINT("R_CRC_W_Open API FAILED \r\n");
        APP_ERR_TRAP(err);
    }

    APP_PRINT("\r\nPress any key for CRC Operation");

    while (true)
    {
        memset(rByte, RESET_VALUE, BUFFER_SIZE_DOWN);
        /* If user input from rtt is valid perform crc operation */
        if (APP_CHECK_DATA)
        {
            APP_READ(rByte);
            /* Notify user the start of CRC operation*/
            APP_PRINT("\r\nStart CRC Operation\r\n");

            /*Perform CRC operation */
            err = crc_operation();

            /* Handle error */
            if (FSP_SUCCESS != err)
            {
                /* Turn on LED as sign of CRC operation failure */
                set_led(LED_ON);

                /* print RTT message */
                APP_ERR_PRINT("\r\n ** CRC operation failed ** \r\n");
                /* close all the opened modules before trap */
                cleanup();
                APP_ERR_TRAP(err);
            }

            APP_PRINT("\r\nPress any key for CRC Operation");
        }
    }
}

/*******************************************************************************************************************//**
 *  @brief      Performs CRC calculation in normal and snoop mode and toggle LED on successful operation
 *              else Turn LED ON on failure. Also displays failure messages in RTT.
 *  @param[IN]  None
 *  @retval     FSP_SUCCESS    On successfully CRC result in snoop and normal operation mode.
 *  @retval     err            Any Other Error code apart from FSP_SUCCES  Unsuccessful operation.
 **********************************************************************************************************************/
static fsp_err_t crc_operation(void)
{
    fsp_err_t err = FSP_SUCCESS;
    /* CRC inputs structure */
    crc_input_t input_data;
    crc_input_t rx_input_data;
    uint32_t normal_crc_value = RESET_VALUE; //CRC value in normal mode
    uint32_t rx_normal_crc_value = RESET_VALUE; //CRC value in Snoop mode
    uint32_t uart_time_out = UINT32_MAX; // Timeout value to check Rx, Tx events
    uint8_t input_buffer[BUF_LEN] = { 0x05, 0x02, 0x03, 0x04 }; // Source data
    uint8_t dest_buffer[BUF_LEN] = {RESET_VALUE}; //Buffer to store UART read data
    uint8_t uart_data_len = RESET_VALUE; //Data length for polynomial operation
    uint8_t rx_crc_value[NUM_BYTES] = {RESET_VALUE}; // Received CRC value from UART
    uint8_t crc_length = 0;
    crc_w_extended_cfg_t *p_cfg_extend;

    /* Before beginning the operation turn off LED */
    set_led(LED_OFF);

    /*clear callback event flag */
    w_uart_rxflag = false;
    w_uart_txflag = false;

    p_cfg_extend = (crc_w_extended_cfg_t*) g_crc_cfg.p_extend;

    /* update seed value and transfer uart_data_len as per the polynomial used */
    if ((CRC_W_POLYNOMIAL_CRC_32 == p_cfg_extend->polynomial) ||
        (CRC_W_POLYNOMIAL_CRC_32C == p_cfg_extend->polynomial))
    {
        uart_data_len = THIRTYTWO_BIT_DATA_LEN;  //Data length for 32 bit polynomial operation
        crc_length = 4;        // 32 bit
    }
    else if ((CRC_W_POLYNOMIAL_CRC_16_CCITT == p_cfg_extend->polynomial) ||
             (CRC_W_POLYNOMIAL_CRC_16_IBM == p_cfg_extend->polynomial))
    {
        uart_data_len = SIXTEEN_BIT_DATA_LEN;  //Data length for 16 bit polynomial operation
        crc_length = 2;        // 16 bit
    }
    else
    {
        /* Display failure message in RTT */
        APP_ERR_PRINT("UNSUPPORTED CRC POLYNOMIAL SELECECTED \r\n");

        return FSP_ERR_UNSUPPORTED;
    }

    /* update CRC input structure for normal mode */
    input_data.num_bytes = NUM_BYTES;
    input_data.crc_seed = SEED_VALUE;
    input_data.p_input_buffer = &input_buffer;

    /* calculate crc value for input data in Normal mode */
    err = R_CRC_W_Calculate(&g_crc_ctrl, &input_data, &normal_crc_value);
    if (FSP_SUCCESS != err)
    {
        /* Display failure message in RTT */
        APP_ERR_PRINT("R_CRC_Calculate API FAILED \r\n");

        return err;
    }

    APP_PRINT("[%s] normal_crc_value = 0x%X\r\n", __func__, normal_crc_value);

    /* append calculated CRC value from normal mode to input buffer */
    if ((CRC_W_POLYNOMIAL_CRC_32 == p_cfg_extend->polynomial) ||
        (CRC_W_POLYNOMIAL_CRC_32C == p_cfg_extend->polynomial))
    {
        /* extract the bytes from 16 bit CRC value and append to input buffer as per the selected byte order
         * in CRC configuration.*/
        if (CRC_W_ENDIAN_LITTLE == p_cfg_extend->endian_type)
        {
            input_buffer[4] = (uint8_t) (normal_crc_value & 0xFF);
            input_buffer[5] = (uint8_t) ((normal_crc_value >> 8) & 0xFF);
            input_buffer[6] = (uint8_t) ((normal_crc_value >> 16) & 0xFF);
            input_buffer[7] = (uint8_t) ((normal_crc_value >> 24) & 0xFF);
        }
        else
        {
            input_buffer[7] = (uint8_t) (normal_crc_value & 0xFF);       //extract first byte
            input_buffer[6] = (uint8_t) ((normal_crc_value >> 8) & 0xFF); //extract second byte
            input_buffer[5] = (uint8_t) ((normal_crc_value >> 16) & 0xFF);       //extract first byte
            input_buffer[4] = (uint8_t) ((normal_crc_value >> 24) & 0xFF); //extract second byte
        }
    }
    else if ((CRC_W_POLYNOMIAL_CRC_16_CCITT == p_cfg_extend->polynomial) ||
             (CRC_W_POLYNOMIAL_CRC_16_IBM == p_cfg_extend->polynomial))
    {
        /* extract the bytes from 16 bit CRC value and append to input buffer as per the selected byte order
         * in CRC configuration.*/
        if (CRC_W_ENDIAN_LITTLE == p_cfg_extend->endian_type)
        {
            input_buffer[4] = (uint8_t) (normal_crc_value & 0xFF);       //extract first byte
            input_buffer[5] = (uint8_t) ((normal_crc_value >> 8) & 0xFF); //extract second byte
        }
        else
        {
            input_buffer[5] = (uint8_t) (normal_crc_value & 0xFF);       //extract first byte
            input_buffer[4] = (uint8_t) ((normal_crc_value >> 8) & 0xFF); //extract second byte
        }
    }
    else
    {
        /*do nothing */
    }

    /* Perform SCI UART loop-back transmission from TX to RX*/
    /* Perform uart write operation */
    err = R_UART_W_Write(&g_uart_ctrl, input_buffer, uart_data_len);
    if (FSP_SUCCESS != err)
    {
        /* Display failure message in RTT */
        APP_ERR_PRINT("R_UART_W_Write API FAILED \r\n");

        return err;
    }

    /* Perform uart read operation */
    err = R_UART_W_Read(&g_uart_ctrl, dest_buffer, uart_data_len);
    if (FSP_SUCCESS != err)
    {
        /* Display failure message in RTT */
        APP_ERR_PRINT("R_UART_W_Read API FAILED \r\n");

        return err;
    }

    /* wait for tx and rx complete event */
    while ((true != w_uart_txflag) || (true != w_uart_rxflag))
    {
        /*start checking for timeout to avoid infinite loop*/
        --uart_time_out;

        /*check for time elapse*/
        if (RESET_VALUE == uart_time_out)
        {
            /*we have reached to a scenario where uart tx and rx events not occurred*/
            APP_ERR_PRINT(" ** Uart tx and rx events not received during uart write or read operation **\r\r");

            return FSP_ERR_TIMEOUT;
        }
    }

    /* update CRC input structure for normal mode */
    rx_input_data.num_bytes = strlen((char*) dest_buffer) - crc_length;
    rx_input_data.crc_seed = SEED_VALUE;
    rx_input_data.p_input_buffer = &dest_buffer;

    /* calculate crc value for rx input data in Normal mode */
    err = R_CRC_W_Calculate(&g_crc_ctrl, &rx_input_data, &rx_normal_crc_value);
    if (FSP_SUCCESS != err)
    {
        /* Display failure message in RTT */
        APP_ERR_PRINT("R_CRC_W_Calculate API FAILED \r\n");

        return err;
    }

    APP_PRINT("[%s] rx_normal_crc_value = 0x%X, dest_buffer len(%d)\r\n", __func__, rx_normal_crc_value,
              strlen((char* )dest_buffer));

    if ((CRC_W_POLYNOMIAL_CRC_32 == p_cfg_extend->polynomial) ||
        (CRC_W_POLYNOMIAL_CRC_32C == p_cfg_extend->polynomial))
    {
        /* extract the bytes from 16 bit CRC value and append to input buffer as per the selected byte order
         * in CRC configuration.*/
        if (CRC_W_ENDIAN_LITTLE == p_cfg_extend->endian_type)
        {
            rx_crc_value[0] = (uint8_t) (rx_normal_crc_value & 0xFF);
            rx_crc_value[1] = (uint8_t) ((rx_normal_crc_value >> 8) & 0xFF);
            rx_crc_value[2] = (uint8_t) ((rx_normal_crc_value >> 16) & 0xFF);
            rx_crc_value[3] = (uint8_t) ((rx_normal_crc_value >> 24) & 0xFF);
        }
        else
        {

            rx_crc_value[3] = (uint8_t) (rx_normal_crc_value & 0xFF);
            rx_crc_value[2] = (uint8_t) ((rx_normal_crc_value >> 8) & 0xFF);
            rx_crc_value[1] = (uint8_t) ((rx_normal_crc_value >> 16) & 0xFF);
            rx_crc_value[0] = (uint8_t) ((rx_normal_crc_value >> 24) & 0xFF);
        }
    }
    else if ((CRC_W_POLYNOMIAL_CRC_16_CCITT == p_cfg_extend->polynomial) ||
             (CRC_W_POLYNOMIAL_CRC_16_IBM == p_cfg_extend->polynomial))
    {
        /* extract the bytes from 16 bit CRC value and append to input buffer as per the selected byte order
         * in CRC configuration.*/
        if (CRC_W_ENDIAN_LITTLE == p_cfg_extend->endian_type)
        {
            rx_crc_value[0] = (uint8_t) (rx_normal_crc_value & 0xFF);       //extract first byte
            rx_crc_value[1] = (uint8_t) ((rx_normal_crc_value >> 8) & 0xFF); //extract second byte
        }
        else
        {
            rx_crc_value[1] = (uint8_t) (rx_normal_crc_value & 0xFF);       //extract first byte
            rx_crc_value[0] = (uint8_t) ((rx_normal_crc_value >> 8) & 0xFF); //extract second byte
        }
    }

#ifdef CRC_DATA_DEBUG
    {
        int i = 0;

        APP_PRINT("\r\n\r\n\t RX CRC:\t");
        for (i = 0; i < NUM_BYTES; i++)
        {
           APP_PRINT("0x%02X ", rx_crc_value[i]);
        }

        APP_PRINT("\r\n\t DEST:\t");
        for (i = 0; i < NUM_BYTES; i++)
        {
            APP_PRINT("0x%02X ", dest_buffer[NUM_BYTES+i]);
        }

        APP_PRINT("\r\n\r\n");
    }
#endif

    /* validate the CRC results */
    if (strncmp((char*) rx_crc_value, (char*) (dest_buffer + NUM_BYTES), crc_length) == 0)
    {
        APP_PRINT("\r\nCRC Operation is successful.  \r\n");

        /* compare uart write and read data buffer */
        if (RESET_VALUE == memcmp(dest_buffer, input_buffer, uart_data_len))
        {
            APP_PRINT("Uart transmitted and received data successfully. \r\n");
            /* toggle led as sign of successful operation */
            toggle_led();
        }
    }
    else
    {
        APP_ERR_PRINT("UART loop-back transmission error \r\n");

        return FSP_ERR_ABORTED;
    }

    return err;
}

/*******************************************************************************************************************//**
 *  @brief           User defined sci uart driver callback function to indicate occurrence of Rx,Tx events
 *  @param[IN]       p_args
 *  @retval          None
 **********************************************************************************************************************/
void uart_cb(uart_callback_args_t *p_args)
{
    if (NULL != p_args)
    {
        switch (p_args->event)
        {
            case UART_EVENT_RX_COMPLETE:
                w_uart_rxflag = true;
                break;

            case UART_EVENT_TX_COMPLETE:
                w_uart_txflag = true;
                break;

            default:
                break;
        }
    }
}

/*******************************************************************************************************************//**
 * This function is called to do closing of crc module using its HAL level API.
 * @brief     Close the crc module. Handle the Error internally with Proper Message.
 *            Application handles the rest.
 * @param[IN] None
 * @retval    None
 **********************************************************************************************************************/
void deinit_crc(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* close opened crc module */
    err = R_CRC_W_Close(&g_crc_ctrl);
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** R_CRC_W_Close API FAILED **\r\n");
    }
}

/*******************************************************************************************************************//**
 * This function is called to do closing of sci uart module using its HAL level API.
 * @brief     Close the sci uart module. Handle the Error internally with Proper Message.
 *            Application handles the rest.
 * @param[IN] None
 * @retval    None
 **********************************************************************************************************************/
void deinit_uart(void)
{
    fsp_err_t err = FSP_SUCCESS;

    /* close opened External IRQ module */
    err = R_UART_W_Close(&g_uart_ctrl);
    /* Handle error */
    if (FSP_SUCCESS != err)
    {
        APP_ERR_PRINT("** R_UART_W_Close API FAILED **\r\n");
    }
}

/*******************************************************************************************************************//**
 * @brief     This function is called to do closing of all opened module.
 * @param[IN] None
 * @retval    None
 **********************************************************************************************************************/
void cleanup(void)
{
    /* close all the opened modules  */
    deinit_crc();
    deinit_uart();
}

/*******************************************************************************************************************//**
 * @brief     Toggle on board LED, which are connected and supported by BSP
 * @param[IN] None
 * @retval    None
 **********************************************************************************************************************/
void toggle_led(void)
{
    #define LED_BLINK_CNT 3
    for (int i = 0; i < LED_BLINK_CNT; i++)
    {
        set_led(LED_ON);
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
        set_led(LED_OFF);
        R_BSP_SoftwareDelay(500, BSP_DELAY_UNITS_MILLISECONDS);
    }
}

/*******************************************************************************************************************//**
 *  @brief       Turn on_board LED ON or OFF.
 *  @param[IN]   onoff     LED_ON or LED_OFF
 *  @retval      None
 **********************************************************************************************************************/
static fsp_err_t set_led(uint32_t onoff)
{
    fsp_err_t err = FSP_SUCCESS;

    if (onoff == LED_ON)
    {
        err = R_GPIO_W_PinWrite(&g_gpio_w_ctrl, (bsp_io_port_pin_t) BSP_IO_PORT_00_PIN_10, BSP_IO_LEVEL_HIGH);
    }
    else if (onoff == LED_OFF)
    {
        err = R_GPIO_W_PinWrite(&g_gpio_w_ctrl, (bsp_io_port_pin_t) BSP_IO_PORT_00_PIN_10, BSP_IO_LEVEL_LOW);
    }
    else
    {
        APP_ERR_PRINT("\r\n **  Invalid parameter of LED on/off  ** \r\n");
        err = FSP_ERR_INVALID_ARGUMENT;
    }

    return err;
}

/*******************************************************************************************************************//**
 * This function is called at various points during the startup process.  This implementation uses:
 *  - the event that is called after the clocks have been configured, to freeze the watchdog
 *  - the event that is called right before main() to set up the pins
 *
 * @param[in]  event    Where at in the start up process the code is currently at
 **********************************************************************************************************************/
void R_BSP_WarmStart(bsp_warm_start_event_t event)
{
    if (BSP_WARM_START_RESET == event)
    {
    }

    if (BSP_WARM_START_POST_CLOCK == event)
    {
        /* System clocks are configured. */

        /*
         * Freeze the watchdog, to avoid an unexpected reboot.
         * The watchdog-freeze setting must be enabled for this to have an effect.
         */
        R_BSP_PeripheralFreeze (BSP_FREEZE_PERIPHERAL_SYS_WDOG);
    }

    if (BSP_WARM_START_POST_C == event)
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins. */
        R_GPIO_W_Open (&g_gpio_w_ctrl, &IOPORT_CFG_NAME);
    }
}

#if BSP_TZ_SECURE_BUILD
FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{
}
FSP_CPP_FOOTER
#endif
